-- CreateEnum
CREATE TYPE "TRANSPORT_MODE" AS ENUM ('DRIVE', 'WALK', 'BICYCLE', 'TRANSIT', 'TWO_WHEELER');

-- AlterTable
ALTER TABLE "Route" ADD COLUMN     "transportMode" "TRANSPORT_MODE" DEFAULT 'DRIVE';
